import { WeaponConfig, WeaponType } from '../types/game';

export const WEAPONS: Record<WeaponType, WeaponConfig> = {
  pistol: {
    id: 'pistol',
    name: 'Pistol',
    damage: 24,
    ammoMax: 12,
    ammoReserve: 60,
    fireRate: 3.5, // shots per sec
    reloadTime: 1.0,
    bulletSpeed: 800,
    spread: 0.03,
    color: '#64748b',
    bulletColor: '#facc15',
    bulletRadius: 3.5,
    isOneHanded: true,
    recoil: 2.5,
    icon: '🔫',
  },
  revolver: {
    id: 'revolver',
    name: '.44 Magnum',
    damage: 52,
    ammoMax: 6,
    ammoReserve: 36,
    fireRate: 2.2,
    reloadTime: 1.5,
    bulletSpeed: 950,
    spread: 0.02,
    color: '#94a3b8',
    bulletColor: '#fef08a',
    bulletRadius: 4.2,
    isOneHanded: true,
    recoil: 7.5,
    icon: '🤠',
  },
  smg: {
    id: 'smg',
    name: 'SMG',
    damage: 17,
    ammoMax: 30,
    ammoReserve: 150,
    fireRate: 9.5, // fast spray
    reloadTime: 1.3,
    bulletSpeed: 880,
    spread: 0.1,
    color: '#0284c7',
    bulletColor: '#38bdf8',
    bulletRadius: 3.2,
    isOneHanded: true,
    recoil: 3.5,
    icon: '⚡',
  },
  minigun: {
    id: 'minigun',
    name: 'Rotary Minigun',
    damage: 16,
    ammoMax: 80,
    ammoReserve: 240,
    fireRate: 14.0, // insane suppressive fire
    reloadTime: 2.4,
    bulletSpeed: 920,
    spread: 0.14,
    color: '#334155',
    bulletColor: '#fde047',
    bulletRadius: 3.2,
    isOneHanded: false,
    recoil: 6.0,
    icon: '⚙️',
  },
  flamethrower: {
    id: 'flamethrower',
    name: 'Flamethrower',
    damage: 14, // Rapid burning ticks
    ammoMax: 60,
    ammoReserve: 180,
    fireRate: 11.0,
    reloadTime: 1.8,
    bulletSpeed: 480,
    spread: 0.18,
    color: '#ea580c',
    bulletColor: '#f97316',
    bulletRadius: 6.0,
    isOneHanded: false,
    recoil: 2.0,
    icon: '🔥',
  },
  plasma: {
    id: 'plasma',
    name: 'Plasma Carbine',
    damage: 34,
    ammoMax: 24,
    ammoReserve: 96,
    fireRate: 6.0,
    reloadTime: 1.2,
    bulletSpeed: 1050,
    spread: 0.02,
    color: '#06b6d4',
    bulletColor: '#67e8f9',
    bulletRadius: 5.5,
    isOneHanded: false,
    recoil: 3.0,
    icon: '🔋',
  },
  saw: {
    id: 'saw',
    name: 'Saw Launcher',
    damage: 68,
    ammoMax: 6,
    ammoReserve: 24,
    fireRate: 1.5,
    reloadTime: 1.7,
    bulletSpeed: 640,
    spread: 0.02,
    color: '#e11d48',
    bulletColor: '#e2e8f0',
    bulletRadius: 8.5,
    isOneHanded: false,
    recoil: 8.0,
    icon: '🪚',
  },
  rifle: {
    id: 'rifle',
    name: 'AK Rifle',
    damage: 32,
    ammoMax: 30,
    ammoReserve: 120,
    fireRate: 6.2,
    reloadTime: 1.6,
    bulletSpeed: 950,
    spread: 0.05,
    color: '#b45309',
    bulletColor: '#f59e0b',
    bulletRadius: 4.0,
    isOneHanded: false,
    recoil: 5.5,
    icon: '💥',
  },
  shotgun: {
    id: 'shotgun',
    name: 'Shotgun',
    damage: 18, // per pellet * 6 = 108 damage point blank!
    ammoMax: 6,
    ammoReserve: 36,
    fireRate: 1.2,
    reloadTime: 1.8,
    bulletSpeed: 720,
    spread: 0.22,
    pellets: 6,
    color: '#dc2626',
    bulletColor: '#fb923c',
    bulletRadius: 3.5,
    isOneHanded: false,
    recoil: 9.0,
    icon: '🔴',
  },
  sniper: {
    id: 'sniper',
    name: 'Sniper Rifle',
    damage: 90,
    ammoMax: 4,
    ammoReserve: 24,
    fireRate: 0.8,
    reloadTime: 2.2,
    bulletSpeed: 1400,
    spread: 0.01,
    color: '#059669',
    bulletColor: '#34d399',
    bulletRadius: 4.5,
    isOneHanded: false,
    recoil: 12.0,
    icon: '🎯',
  },
  rocket: {
    id: 'rocket',
    name: 'Rocket Launcher',
    damage: 115,
    ammoMax: 3,
    ammoReserve: 15,
    fireRate: 0.7,
    reloadTime: 2.5,
    bulletSpeed: 580,
    spread: 0.02,
    color: '#7c3aed',
    bulletColor: '#c084fc',
    bulletRadius: 7.0,
    isExplosive: true,
    isOneHanded: false,
    recoil: 11.0,
    icon: '🚀',
  },
  grenade: {
    id: 'grenade',
    name: 'Hand Grenade',
    damage: 110,
    ammoMax: 3,
    ammoReserve: 6,
    fireRate: 1.0,
    reloadTime: 1.0,
    bulletSpeed: 550,
    spread: 0.05,
    color: '#65a30d',
    bulletColor: '#84cc16',
    bulletRadius: 6.5,
    isExplosive: true,
    isOneHanded: true,
    recoil: 2.0,
    icon: '💣',
  },
};
